name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20.11.1', '21.5.0']

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Setup PNPM Environment
        uses: ./.github/actions/setup-pnpm
        with:
          node-version: ${{ matrix.node-version }}
          pnpm-version: '8'

      - name: Lint
        run: pnpm lint

      - name: Type check
        run: pnpm run type-check

      - name: Build
        run: pnpm build

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run unit tests
        run: pnpm test

      - name: Check test coverage
        run: pnpm test:coverage

      - name: Verify import paths
        run: 'pnpm lint --rule "import/no-unresolved: 2"'

      - name: Save test results
        if: always()
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
        with:
          name: test-results
          path: coverage
          retention-days: 14

  a11y:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Setup PNPM Environment
        uses: ./.github/actions/setup-pnpm
        with:
          node-version: '20.x'
          pnpm-version: '8'

      - name: Build
        run: pnpm build

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Установка axe-core
        run: pnpm add axe-core @axe-core/playwright

      - name: Запуск a11y тестов
        run: pnpm run test:a11y

  e2e:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Setup PNPM Environment
        uses: ./.github/actions/setup-pnpm
        with:
          node-version: '20.x'
          pnpm-version: '8'

      - name: Build
        run: pnpm build

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run E2E Tests
        run: pnpm run test:e2e

      - name: Run Component A11y Tests
        run: pnpm run test:components-a11y
